### PR TITLE
fix: remove arg with None, add option to completely replace lists, checks whether condition has transition or not

### PR DESCRIPTION
**Pull request by jobcespedes**
fixes https://github.com/operator-framework/operator-sdk-ansible-util/issues/12
fixes https://github.com/operator-framework/operator-sdk-ansible-util/issues/19
fixes https://github.com/operator-framework/operator-sdk-ansible-util/issues/21

### CODE REVIEW

**Comment by fabianvf** [comment]
Oh man thanks for this contribution, I didn't have the repo notification set up properly (feel free to ping me directly if things are hanging around). Taking a look now

**Review by fabianvf — APPROVED** [review]
/lgtm

If you wanted to, we now have actual tests (you could add the test tasks here https://github.com/operator-framework/operator-sdk-ansible-util/blob/master/molecule/default/tasks/advanced_usage.yml), but all these changes look sane to me so as long as the current tests pass I'm happy to go back later and add some regression tests

**Comment by jobcespedes** [comment]
Glad to contribute a little or at least propose some fixes. I will consider sending a direct message in any case. Thanks

**Comment by jobcespedes** [comment]
> If you wanted to, we now have actual tests

Thanks for the pointer. I didn't know about them. I'll keep in mind that too.

**Comment by fabianvf** [comment]
>  Thanks for the pointer. I didn't know about them. I'll keep in mind that too.

yeah they're very recent (we probably should have had them from the start :grimacing:).

**Pull request merged**
